spring.application.name=notas

spring.data.mongodb.database=asistente_diario
spring.data.mongodb.uri=mongodb://localhost:27017
server.port=8081

jwt.secret=${JWT_SECRET}
jwt.expiration=86400

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=5000
logging.level.org.apache.kafka.clients.producer=INFO
logging.level.com.asistente.notas.eventos=INFO




